project_id = "lxjhrnbxwknobcgnuruk"

[functions.send-reminders]
verify_jwt = false

[functions.generate-sound]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = true

[functions.check-streaks]
verify_jwt = false

[functions.zouti-webhook]
verify_jwt = false

[functions.send-subscription-notifications]
verify_jwt = false

[functions.generate-recaps]
verify_jwt = false

[functions.get-holidays]
verify_jwt = false

[functions.notion-oauth-callback]
enabled = true
verify_jwt = true
import_map = "./functions/notion-oauth-callback/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notion-oauth-callback/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notion-oauth-callback/*.html" ]

[functions.notion-list-databases]
enabled = true
verify_jwt = true
import_map = "./functions/notion-list-databases/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notion-list-databases/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notion-list-databases/*.html" ]

[functions.notion-import-database]
enabled = true
verify_jwt = true
import_map = "./functions/notion-import-database/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notion-import-database/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notion-import-database/*.html" ]
